Tests
rdcaldwell/FiscJanitor pull request #2
Opened 2018-04-04 01:06 UTC by jzbass25

Additions
- Added/Fixed more Karma tests
- Added RDS and EFS Tests, commented out MockBackend Tests

Issues
- RDS describeTagsById should describe by id error and EFS describeTagsById should describe by id error  are getting an error message saying callback is not a function. I fixed this in EFS Describe by removing the {} in line 13 of the controller. I believe something with passing parameters is causing an issue with the callback. 
- There is still an issue with the Analytics and Login Components, Login is more a logical problem on my part and Analytics seems to be caused by the dialog, providing MAT_DIALOG_DATA with some fake data doesn't work despite it working on the Janitor Dialog (line 20 of janitordialog.component.spec.ts).

2018-04-04 02:00 UTC, rdcaldwell requested changes

2018-04-04 02:00 UTC, rdcaldwell commented on src/api/test/rds.js
> +        res.json(res._getData())
remove this line

2018-04-04 02:00 UTC, rdcaldwell commented on src/api/test/rds.js
> +      AWS.mock('RDS', 'listTagsForResource', (callback) => {
AWS.mock('RDS', 'listTagsForResource', ({}, callback) => {

2018-04-04 02:00 UTC, rdcaldwell commented on src/api/test/efs.js
> +        res.json(res._getData())
remove

2018-04-04 02:00 UTC, rdcaldwell commented on src/api/test/efs.js
> +      AWS.mock('EFS', 'describeTags', (callback) => {
AWS.mock('EFS', 'describeTags', ({}, callback) => {

2018-04-04 02:49 UTC, jzbass25 commented
Changes done, fixed the callback issues. Thanks

2018-04-06 22:56 UTC, rdcaldwell approved these changes

2018-04-06 23:37 UTC, merged